packages:
  - 'packages/*'
  - 'examples/*'
  - 'apps/*'
allowBuilds:
  sharp: false

catalogs:
  default:
    # Build & Tooling
    '@types/node': '^22.15.3'
    '@types/react': '19.2.2'
    '@types/react-dom': '19.2.2'
    '@vitest/coverage-v8': '^4.1.1'
    tsup: '^8.5.1'
    typescript: '5.9.2'
    oxfmt: '^0.42.0'
    oxlint: '^1.57.0'
    vitest: '4.1.1'
    knip: '^6.0.4'
    '@changesets/cli': '^2.30.0'
    '@edge-runtime/vm': '^5.0.0'
    zod: '^4.3.6'
    'eslint-plugin-jsdoc': '^62.9.0'

    # Tooling Orchestration
    turbo: '^2.8.20'

    # AI SDK Stack
    ai: '^6.0.138'
    '@ai-sdk/provider': '^3.0.8'
    '@openrouter/ai-sdk-provider': '^2.3.3'

    # Next.js & React
    next: '16.2.0'
    react: '^19.2.0'
    'react-dom': '^19.2.0'
